version: 1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: dotnet restore
build:
  project: VirtualPinball.Database.Models/VirtualPinball.Database.Models.csproj
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: oyZBQLZWaJTZ0HZ9MVIdLzm2fhkduzef9l3v7G1D19pXImhPoAh1E8PRtS053ZQV
  on:
    branch: main
skip_commits:
  files:
    - .github/*
    - readme.md
    - .gitignore
    - .gitattributes